### PR TITLE
Make sure to generate annotations while building.

### PR DESCRIPTION
**Pull request by rleonid**
Surprising that I hadn't used this before.

### CODE REVIEW

**Comment by dsheets** [comment]
You can put this setting in the `_tags` file with something like:

```
true: annot
```

You might also want the `bin-annot` flag to produce `cmt` and `cmti` files which are useful for merlin's source navigation and can be used to generate compiler-directed documentation.

You can do that with:

```
true: annot, bin_annot
```

Other useful tags you might include are `debug` and `principal`.

**Comment by rleonid** [comment]
Thank you. I added `bin_annot` and `principal` in https://github.com/rleonid/oml/pull/76, but I'll leave out `debug` for now as I don't use the debugger all that much. If you find it useful, perhaps I can add another build target?

**Comment by dsheets** [comment]
`debug` is useful because it allows stack trace generation to include call sites that traverse your library. My understanding is that it is only about the inclusion of these symbols and so slightly increases binary size without run-time cost.

**Comment by rleonid** [comment]
Sounds good. I'm wrapped up with build problems at the moment, so I'm going to file an issue to address this later (so I don't forget!).

**Pull request merged**
