### PR TITLE
Use bisect ppx

### PR DESCRIPTION
**Pull request by rleonid**
@struktured Could you check to see if this works for you?

``` Bash
opam install bisect bisect_ppx kaputt
make covered_test
make report
open report_dir/index.html 
```

### CODE REVIEW

**Comment by struktured** [comment]
Modified your comment to list all the necessary test deps. It worked for me, took a couple minutes on an old generation i7 desktop.

**Comment by struktured** [comment]
Also, I don't have the "open" command, apparently.

**Comment by rleonid** [comment]
Oh yea, forgot about all of the other dependencies. Even though I'm tracking them in `make setup` . I don't think we need `bisect` in there, `bisect_ppx` comes with the reporting tools too.

Weird, I guess `open` is just BSD specific.

**Comment by struktured** [comment]
It failed to run without bisect installed for me. Maybe it's an easy fix
though.

**Pull request merged**
